title = "Vincent Behar"
baseURL = "https://vincent.behar.name/"
theme = "hugo-resume"
languageCode = "en-us"
publishDir = "_site"
resourceDir = ".cache/resources"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = true

[params]
    firstName = "Vincent"
    lastName = "Behar"
    address = "Paris, France"
    phone = "00 33 6 89 85 69 80"
    contactNote = "Dev Tools Engineer"
    profileImage = "img/vbehar.jpg"
    email = "vincent@behar.name"
    description = "Software Engineer with 17+ years of experience. I'm a developer, and I love it ;-) Open-source contributor/maintainer, occasional speaker/blogger. My buzzwords of the moment are Go, Kubernetes, Continuous Delivery, Observability, GenAI, ..."
    favicon = "favicon.ico"
    # what sections
    showSkills = true
    showProjects = true
    showOpenSource = true
    showPublications = true
    showAccomplishments = true
    showExperience = true
    showEducation = true

    showBlog = false
    showQr = false

    # do you want to show git hash on page footer and link to repo? Add commit prefix here.
    gitCommitPrefix = "https://github.com/vbehar/vbehar.github.io/commit"

[[params.handles]]
    name = "Download Resume"
    link = "/cv/vincent-behar.pdf"
    customIcon = "file-pdf"

[[params.handles]]
    name = "Bluesky"
    link = "https://bsky.app/profile/vbehar.dev/"

[[params.handles]]
    name = "Twitter"
    link = "https://twitter.com/vbehar/"

[[params.handles]]
    name = "Mastodon"
    link = "https://hachyderm.io/@vbehar"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/vbehar/"

[[params.handles]]
    name = "Medium"
    link = "https://medium.com/@vbehar"

[[params.handles]]
    name = "Keybase"
    link = "https://keybase.io/vbehar"

[[params.handles]]
    name = "Fork this repo on GitHub"
    link = "https://github.com/vbehar/vbehar.github.io"
    customIcon = "code-branch"

[params.google.analytics]
    trackerID = "UA-23435653-1"

[outputs]
    home = ["HTML", "JSON"]

[taxonomies]
    tag = "tags"
