name: publish

on:
  push:
    branches:
      - sources

jobs:
  publish:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.138.0'
          extended: true
      - name: Build website with Hugo
        run: hugo --minify

      - name: Setup Nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-20.09
      - name: Build CV with lualatex in Nix
        # need to run it twice to get the `LastPage`
        run: |
          nix-shell --command 'lualatex -interaction=nonstopmode vincent-behar.tex; lualatex -interaction=nonstopmode vincent-behar.tex'
          cp vincent-behar.pdf ../_site/cv/vincent-behar.pdf
        working-directory: ./cv

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master
          publish_dir: ./_site
          cname: vincent.behar.name
